//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiDefaultApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiDefaultApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Sample App.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main.
        /// </summary>
        internal static string BACK_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("BACK_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Required.
        /// </summary>
        internal static string CALENDAR_PERMISSION_HEADER {
            get {
                return ResourceManager.GetString("CALENDAR_PERMISSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use calendar to add evants. Please enable Calendar Permission in the Settings..
        /// </summary>
        internal static string CALENDAR_PERMISSION_MESSAGE_RATIONALE {
            get {
                return ResourceManager.GetString("CALENDAR_PERMISSION_MESSAGE_RATIONALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Required.
        /// </summary>
        internal static string CAMERA_PERMISSION_HEADER {
            get {
                return ResourceManager.GetString("CAMERA_PERMISSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use camera to scan barcodes and take a photo. Please enable Camera Permission in the Settings..
        /// </summary>
        internal static string CAMERA_PERMISSION_MESSAGE_RATIONALE {
            get {
                return ResourceManager.GetString("CAMERA_PERMISSION_MESSAGE_RATIONALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string DARK_THEME_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("DARK_THEME_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string LANGUAGE_AUTOMATIC {
            get {
                return ResourceManager.GetString("LANGUAGE_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE_BUTTON {
            get {
                return ResourceManager.GetString("LANGUAGE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LANGUAGE_ENGLISH {
            get {
                return ResourceManager.GetString("LANGUAGE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LANGUAGE_GERMAN {
            get {
                return ResourceManager.GetString("LANGUAGE_GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string LANGUAGE_PICKER_TITLE {
            get {
                return ResourceManager.GetString("LANGUAGE_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string LIGHT_THEME_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("LIGHT_THEME_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Required.
        /// </summary>
        internal static string LOCATION_PERMISSION_HEADER {
            get {
                return ResourceManager.GetString("LOCATION_PERMISSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use location information. Please enable Location Permission in the Settings..
        /// </summary>
        internal static string LOCATION_PERMISSION_MESSAGE_RATIONALE {
            get {
                return ResourceManager.GetString("LOCATION_PERMISSION_MESSAGE_RATIONALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MSG_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating personal information: {0}.
        /// </summary>
        internal static string MSG_PERSONAL_INFO_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("MSG_PERSONAL_INFO_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name here....
        /// </summary>
        internal static string NAME_ENTRY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("NAME_ENTRY_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME_ENTRY_TITLE {
            get {
                return ResourceManager.GetString("NAME_ENTRY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Required.
        /// </summary>
        internal static string NOTIFICATION_PERMISSION_HEADER {
            get {
                return ResourceManager.GetString("NOTIFICATION_PERMISSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use notifications to notify user. Please enable Notification Permission in the Settings..
        /// </summary>
        internal static string NOTIFICATION_PERMISSION_MESSAGE_RATIONALE {
            get {
                return ResourceManager.GetString("NOTIFICATION_PERMISSION_MESSAGE_RATIONALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SAVE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("SAVE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change App Theme.
        /// </summary>
        internal static string THEME_LABEL_TEXT {
            get {
                return ResourceManager.GetString("THEME_LABEL_TEXT", resourceCulture);
            }
        }
    }
}
